title: Adam Sanderson # your name (or website title) here
logo: "/images/ProfilePhoto.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MComp Student at Newcastle University, studying Computer Science (Game Engineering)
  <br><br>
  Aspiring video game programmer. Currently looking for my first job in the industry.
  Pleae select a project to view more information.
  <br><br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
